site_name: Lore Engine Documentation
nav:
- Home: index.md
- Overlays:
    - Overlays: effects/overlays.md
    - TintScreen: effects/overlays/tintscreen.md
theme:
    name: mkdocs
    hljs_style: Atelier Dune Dark
    highlightjs: true
    hljs_languages:
        - csharp
