site_name: Lore Engine Documentation
nav:
    - Home: 'index.md'
    - Effects:
        -Effects: 'effects/effects.md'
        -Overlays:
            - Overlays: 'effects/overlays/overlays.md'
            - TintScreen: 'effects/overlays/tintscreen.md'
theme:
    name: mkdocs
    hljs_style: 'Atelier Dune Dark'
    highlightjs: true
    hljs_languages:
        - csharp
