site_name: Lore Engine Documentation
nav:
    - Home: 'index.md'
    - Effects:
        -Effects: '/effects.md'
        -Overlays:
            - Overlays: 'overlays.md'
            - TintScreen: 'tintscreen.md'
theme:
    name: mkdocs
    hljs_style: 'Atelier Dune Dark'
    highlightjs: true
    hljs_languages:
        - csharp
